"""Databricks Asset Bundle (DAB) export — Phase 0.3/0.4 of the gap plan.

Turns a ``run_conversion`` result into a deployable **asset bundle**::

    <name>/
      databricks.yml          bundle + variables + dev/test/prod targets
      resources/
        sfglue_bronze_job.yml Job skeleton running the bronze ingestion notebooks
      src/notebooks/          bronze PySpark notebooks
      dbt/                    the runnable dbt project (delegates to build_dbt_project_files)
      sfglue_state.json       schema-versioned artifact registry (machine-readable manifest)
      README.md

Phase 0 ships the skeleton with today's artifact classes (notebooks + dbt + DDL);
later phases add resource types (full workflows, DQ, grants) by extending
``build_artifact_registry`` + emitting more ``resources/*.yml``.

Deterministic, pure (no I/O, no yaml dependency — templates are strings), fully
unit-testable. Mirrors the contract of ``build_dbt_project_files``:
``build_bundle_files(conversion, destination, name) -> {relative_path: text}``.
"""

from __future__ import annotations

import json
import re

# Version of the migration-state/artifact-registry schema (Phase 0.4). Bump on
# breaking shape changes; consumers (frontend, future phases) switch on it.
SCHEMA_VERSION = 1


def _bundle_name(name: str | None) -> str:
    """Sanitize to a safe bundle/project identifier."""
    n = re.sub(r"[^a-zA-Z0-9_]+", "_", str(name or "").strip()).strip("_").lower()
    return n or "sfglue_migration"


def _yaml_str(value: str) -> str:
    """Quote a scalar for YAML output (double-quoted, escaped)."""
    return json.dumps(str(value if value is not None else ""))


# ─── artifact registry (Phase 0.4) ───────────────────────────────────────────

# artifact classes → the conversion-result key holding them. New phases append
# here (workflow, dq_rule, grant, control_table, …).
_ARTIFACT_SOURCES = (
    ("dbt_model", "dbt_models"),
    ("ddl", "ddl"),
    ("notebook", "notebooks"),
)
_SINGLETON_SOURCES = (
    ("sources_yml", "sources_yml"),
    ("schema_yml", "schema_yml"),
    ("unit_tests_yml", "unit_tests_yml"),
    ("packages_yml", "packages_yml"),
    ("governance_md", "governance_md"),
    ("dq_schema_yml", "dq_schema_yml"),       # Phase 3: compiled dq_rules tests
    ("grants_sql", "grants_sql"),             # Phase 7: LF → UC grant script
    ("outbound_md", "outbound_md"),           # Phase 6: cutover checklist
)
# Phase 1: {workflow_name: dab_yaml} — one resources/*.yml per converted workflow.
_WORKFLOW_KEY = "workflow_yaml"


def build_artifact_registry(conversion: dict) -> list[dict]:
    """Typed inventory of everything a conversion produced.

    Each entry: {id, type, name} (+ later: gate status, target, legacy ref).
    Deterministic order so diffs between runs are meaningful.
    """
    c = conversion or {}
    registry: list[dict] = []
    for a_type, key in _ARTIFACT_SOURCES:
        for name in sorted((c.get(key) or {}).keys()):
            registry.append({"id": f"{a_type}:{name}", "type": a_type, "name": name})
    for a_type, key in _SINGLETON_SOURCES:
        if c.get(key):
            registry.append({"id": f"{a_type}:{key}", "type": a_type, "name": key})
    for name in sorted((c.get(_WORKFLOW_KEY) or {}).keys()):
        registry.append({"id": f"workflow:{name}", "type": "workflow", "name": name})
    return registry


def build_state_manifest(conversion: dict) -> str:
    """The machine-readable migration manifest shipped inside every export."""
    return json.dumps({
        "schemaVersion": SCHEMA_VERSION,
        "generator": "sfglue",
        "artifacts": build_artifact_registry(conversion),
    }, indent=2) + "\n"


# ─── databricks.yml + resources ──────────────────────────────────────────────

def _generate_databricks_yml(destination: dict, name: str) -> str:
    d = destination or {}
    host = d.get("workspace_url") or d.get("workspaceUrl") or d.get("host") or ""
    catalog = d.get("catalog") or "main"
    warehouse = d.get("sql_warehouse_id") or d.get("sqlWarehouseId") or ""
    return f"""# Databricks Asset Bundle — generated by sfglue (schema v{SCHEMA_VERSION}).
# Deploy:   databricks bundle validate && databricks bundle deploy -t dev
# Promote:  databricks bundle deploy -t test | -t prod   (CI is the intended driver)
bundle:
  name: {_yaml_str(name)}

variables:
  catalog:
    description: Target Unity Catalog catalog
    default: {_yaml_str(catalog)}
  warehouse_id:
    description: SQL Warehouse for SQL/dbt tasks
    default: {_yaml_str(warehouse)}

include:
  - resources/*.yml

targets:
  dev:
    mode: development
    default: true
    workspace:
      host: {_yaml_str(host)}
  test:
    mode: development
    workspace:
      host: {_yaml_str(host)}  # TODO: test workspace host
    variables:
      catalog: {_yaml_str(catalog + "_test" if catalog else "test")}
  prod:
    mode: production
    workspace:
      host: {_yaml_str(host)}  # TODO: prod workspace host
    variables:
      catalog: {_yaml_str(catalog + "_prod" if catalog else "prod")}
"""


def _generate_bronze_job_yml(notebooks: dict, name: str) -> str:
    """Job resource running each bronze ingestion notebook.

    Phase 0 skeleton: tasks are independent (no depends_on) — real sequencing
    arrives with the Phase-1 orchestration converter, which will emit the
    workflow-derived DAG here instead.
    """
    lines = [
        f"# Bronze ingestion job — generated by sfglue. Phase-1 replaces this with",
        f"# the Glue-workflow-derived DAG (schedules, depends_on, notifications).",
        "resources:",
        "  jobs:",
        f"    {name}_bronze_ingest:",
        f"      name: {_yaml_str(name + ' — bronze ingest')}",
        "      max_concurrent_runs: 1",
        "      tasks:",
    ]
    for nb in sorted((notebooks or {}).keys()):
        task_key = _bundle_name(nb.rsplit(".", 1)[0])[:100] or "notebook"
        lines += [
            f"        - task_key: {task_key}",
            "          notebook_task:",
            f"            notebook_path: ../src/notebooks/{nb}",
            "            base_parameters:",
            "              catalog: ${var.catalog}",
        ]
    if not notebooks:
        lines += [
            "        - task_key: placeholder",
            "          notebook_task:",
            "            notebook_path: ../src/notebooks/README",
        ]
    return "\n".join(lines) + "\n"


def build_bundle_files(conversion: dict, destination: dict,
                       project_name: str | None = None,
                       dbt_files: dict | None = None) -> dict:
    """Assemble the asset bundle as ``{relative_path: text}``.

    ``dbt_files`` is the output of ``build_dbt_project_files`` (injected by the
    route so this module keeps zero imports from the migration engine — same
    isolation stance as dbt_build).
    """
    c = conversion or {}
    name = _bundle_name(project_name)
    notebooks = c.get("notebooks") or {}

    files: dict = {
        "databricks.yml": _generate_databricks_yml(destination, name),
        "resources/sfglue_bronze_job.yml": _generate_bronze_job_yml(notebooks, name),
        "sfglue_state.json": build_state_manifest(c),
    }
    for nb_name, code in notebooks.items():
        files[f"src/notebooks/{nb_name}"] = code
    if not notebooks:
        files["src/notebooks/README"] = "No bronze notebooks were generated for this conversion.\n"
    for path, content in (dbt_files or {}).items():
        files[f"dbt/{path}"] = content
    # Later-phase artifact classes (all optional/additive):
    for wf_name, yml in (c.get(_WORKFLOW_KEY) or {}).items():
        safe = _bundle_name(wf_name)
        files[f"resources/workflow_{safe}.yml"] = yml
    if c.get("dq_schema_yml"):
        files["dbt/models/dq_schema.yml"] = c["dq_schema_yml"]
    if c.get("grants_sql"):
        files["governance/grants.sql"] = c["grants_sql"]
    if c.get("outbound_md"):
        files["OUTBOUND_CUTOVER.md"] = c["outbound_md"]
    files["README.md"] = (
        f"# {name} — Databricks Asset Bundle\n\n"
        "Generated by the sfglue migration tool (Snowflake + AWS Glue → Databricks + dbt).\n\n"
        "## Layout\n\n"
        "`databricks.yml` defines the bundle and dev/test/prod targets. `resources/` holds the\n"
        "job definitions, `src/notebooks/` the bronze ingestion notebooks, and `dbt/` a runnable\n"
        "dbt project (see its own README). `sfglue_state.json` is the machine-readable artifact\n"
        f"manifest (schema v{SCHEMA_VERSION}).\n\n"
        "## Deploy\n\n"
        "```bash\n"
        "databricks bundle validate\n"
        "databricks bundle deploy -t dev\n"
        "```\n\n"
        "Promotion to test/prod is intended to run in CI: `databricks bundle deploy -t prod`.\n"
    )
    return files
