"""Outbound/consumption repoint kit (Phase 6 of the gap plan) — pure generators.

The tool does not migrate Informatica mappings or API layers (third-party
systems). It generates everything those consumers need to REPOINT from
Snowflake to Databricks: a per-consumer cutover checklist, connection sheet,
and (optionally) a consumer inventory pulled from Snowflake ACCESS_HISTORY.

Also holds the Phase-5 conversion notes for Snowflake pipeline objects
(tasks/streams/pipes/procedures) — dispositions, not silent drops.
"""

from __future__ import annotations

# Best-effort consumer discovery. Requires Enterprise-edition ACCOUNT_USAGE access;
# the caller treats a failure as "inventory unavailable — enter consumers manually".
ACCESS_HISTORY_SQL = """
select user_name,
       f.value:objectName::string as object_name,
       count(*) as reads,
       max(query_start_time) as last_read
from snowflake.account_usage.access_history,
     lateral flatten(base_objects_accessed) f
where query_start_time > dateadd(day, -90, current_timestamp())
group by 1, 2
order by reads desc
limit 500
""".strip()


def generate_outbound_cutover_md(consumers: list[dict], destination: dict) -> str:
    """The outbound cutover checklist. ``consumers``: [{name, kind, objects: [...]}]
    — from ACCESS_HISTORY (service accounts) or entered manually in review."""
    d = destination or {}
    host = d.get("workspace_url") or "<workspace-url>"
    wh = d.get("sql_warehouse_id") or "<warehouse-id>"
    catalog = d.get("catalog") or "main"
    lines = [
        "# Outbound cutover checklist (generated by sfglue — Phase 6)",
        "",
        "Every external consumer of the legacy Snowflake publish layer, with what it",
        "needs to repoint to Databricks. The tool migrates the DATA; these systems",
        "repoint their CONNECTIONS (third-party config is not auto-migrated).",
        "",
        "## Databricks SQL connection sheet",
        "",
        f"- Server hostname: `{host.replace('https://', '')}`",
        f"- HTTP path: `/sql/1.0/warehouses/{wh}`",
        f"- Catalog: `{catalog}`  ·  Auth: service principal + OAuth (PAT for dev only)",
        "",
        "## Consumers",
        "",
    ]
    for c in consumers or [{"name": "(add consumers here)", "kind": "", "objects": []}]:
        lines.append(f"### {c.get('name')}" + (f"  ·  {c['kind']}" if c.get("kind") else ""))
        for obj in c.get("objects") or []:
            lines.append(f"- [ ] repoint `{obj}` → `{catalog}.gold.{str(obj).split('.')[-1].lower()}`")
        kind = str(c.get("kind") or "").lower()
        if "informatica" in kind or "iics" in kind:
            lines.append("- [ ] swap the IICS Snowflake connection for the Databricks Delta "
                         "connector (same mapping, new connection).")
        if "power bi" in kind or "powerbi" in kind:
            lines.append("- [ ] Power BI: replace the Snowflake source with the Databricks "
                         "connector (Partner Connect) using the sheet above; validate visuals.")
        if "reltio" in kind:
            lines.append("- [ ] Reltio return feed: point the mastered-data drop at the landing "
                         "path; it flows through the standard feed config (control plane).")
        if "file" in kind or "sftp" in kind or "porzio" in kind:
            lines.append("- [ ] File consumer: prefer a Delta Sharing share over regenerated "
                         "file drops (`CREATE SHARE` — see governance notes).")
        lines.append("")
    lines += [
        "## Cutover order",
        "",
        "1. Parallel-run week green (daily reconcile on all feeds).",
        "2. Freeze legacy loads → final reconcile → repoint consumers (above) →",
        "   monitor → decommission legacy publish jobs.",
        "",
    ]
    return "\n".join(lines)


# ─── Phase 5: Snowflake pipeline-object dispositions ─────────────────────────

def snowflake_pipeline_notes(pipeline: dict, destination: dict) -> dict:
    """tasks/streams/pipes/procedures/stages → disposition notes {fname: md}.

    Deterministic dispositions per the plan's conversion table. Tasks with
    schedules also return ``job_task_seeds`` the orchestration engine can fold
    into a Databricks Job.
    """
    p = pipeline or {}
    notes: dict = {}
    seeds: list = []

    tasks = p.get("tasks") or []
    if tasks:
        rows = []
        for t in tasks:
            sched = t.get("schedule") or (f"AFTER {t['predecessors']}" if t.get("predecessors") else "")
            rows.append(f"| {t.get('name')} | {sched or '—'} | {t.get('state','')} | "
                        f"task in the migrated Databricks Job |")
            if t.get("definition"):
                seeds.append({"name": t.get("name"), "sql": t.get("definition"),
                              "schedule": t.get("schedule") or ""})
        notes["_pipeline__tasks.md"] = (
            "# Snowflake TASKs → Databricks Job tasks\n\n"
            "Scheduled SQL tasks become tasks in the generated Databricks Job; AFTER-chains "
            "become `depends_on` edges. Their SQL bodies are listed for conversion.\n\n"
            "| Task | Schedule | State | Disposition |\n|---|---|---|---|\n" + "\n".join(rows) + "\n")

    streams = p.get("streams") or []
    if streams:
        rows = [f"| {s.get('name')} | {s.get('table_name')} | {s.get('mode','')} | "
                "enable Delta Change Data Feed on the migrated table; consumers use "
                "`readChangeFeed` |" for s in streams]
        notes["_pipeline__streams.md"] = (
            "# Snowflake STREAMs → Delta Change Data Feed\n\n"
            "```sql\nALTER TABLE <migrated_table> SET TBLPROPERTIES "
            "(delta.enableChangeDataFeed = true);\n```\n\n"
            "| Stream | Source table | Mode | Disposition |\n|---|---|---|---|\n" + "\n".join(rows) + "\n")

    pipes = p.get("pipes") or []
    if pipes:
        rows = [f"| {x.get('name')} | Auto Loader on the same landing path (see the bronze "
                "ingestion notebook + file-arrival trigger) |" for x in pipes]
        notes["_pipeline__pipes.md"] = (
            "# Snowpipes → Auto Loader\n\n"
            "| Pipe | Disposition |\n|---|---|\n" + "\n".join(rows) +
            "\n\nCOPY definitions are preserved in the introspection payload for reference.\n")

    procs = p.get("procedures") or []
    if procs:
        rows = [f"| {x.get('name')}({x.get('arguments','')}) | port as a Databricks notebook "
                "(procedural) or dbt model (single-statement) — needs its DDL body |" for x in procs]
        notes["_pipeline__procedures.md"] = (
            "# Stored procedures — review queue\n\n"
            "| Procedure | Disposition |\n|---|---|\n" + "\n".join(rows) + "\n")

    stages = p.get("stages") or []
    if stages:
        rows = [f"| {s.get('name')} | {s.get('url') or '(internal)'} | UC external location "
                "+ Auto Loader read options |" for s in stages]
        notes["_pipeline__stages.md"] = (
            "# Stages → UC external locations\n\n"
            "| Stage | URL | Disposition |\n|---|---|---|\n" + "\n".join(rows) + "\n")

    return {"notes": notes, "job_task_seeds": seeds}
