-- Generated by align_reference_config.py — control config aligned with the
-- live Glue catalog + the Glue jobs' contract. Review, then:
--   psql -h localhost -d control -f seed_pipeline_config.sql
BEGIN;

-- 1. configuration_master → real catalog names
UPDATE configuration_master SET curated_database='medaffairs_silver', publish_database='medaffairs_gold';
UPDATE configuration_master SET curated_tablename='account', publish_tablename='dim_account' WHERE source_object_name='account';
UPDATE configuration_master SET curated_tablename='call', publish_tablename='fact_call' WHERE source_object_name='call';
UPDATE configuration_master SET curated_tablename='call_detail', publish_tablename='fact_call_detail' WHERE source_object_name='call_detail';
UPDATE configuration_master SET curated_tablename='call_discussion', publish_tablename='fact_call_discussion' WHERE source_object_name='call_discussion';
UPDATE configuration_master SET curated_tablename='call_expense', publish_tablename='fact_call_expense' WHERE source_object_name='call_expense';
UPDATE configuration_master SET curated_tablename='call_followup', publish_tablename='fact_call_followup' WHERE source_object_name='call_followup';

-- 2. query_configuration — the two interfaces the jobs expect
DELETE FROM query_configuration WHERE interface IN ('raw_to_curated','curated_to_publish');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  `ID` as account_id,
  `Name` as account_name,
  `Account_Type_vod__c` as account_type,
  `FirstName` as first_name,
  `LastName` as last_name,
  concat_ws(' ', `FirstName`, `LastName`) as full_name,
  `Specialty_1_vod__c` as specialty,
  `Credentials_vod__c` as credentials,
  `Primary_Parent_vod__c` as primary_parent_id,
  'N' as dq_orphan_parent,
  '{file_name}' as _source_file,
  '{batch_id}' as _batch_id,
  cast(current_timestamp() as string) as _load_ts,
  cast(current_timestamp() as string) as dwh_silver_ts,
  '{batch_id}' as dwh_batch_id,
  '{batch_id}' as batch_id,
  cast({file_id} as string) as pt_file_id
from {raw_filename}$qq$, 'commercial', 'crm', '*.xlsx', 'raw_to_curated', 'raw_account', 'account', '1');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  account_id,
  account_name,
  account_type,
  first_name,
  last_name,
  full_name,
  specialty,
  credentials,
  primary_parent_id,
  dq_orphan_parent,
  cast(null as string) as account_sk,
  'account' as data_src_nm
from {curated_db}.{curated_tbl_name}
where batch_id = '{batch_id}'$qq$, 'commercial', 'crm', '*.xlsx', 'curated_to_publish', 'account', 'dim_account', '1');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  `Id` as call_id,
  cast(null as string) as call_number,
  `Account_vod__c` as account_id,
  `Call_Date_vod__c` as call_date,
  cast(null as string) as call_datetime,
  `Status_vod__c` as status,
  cast(null as string) as is_completed,
  `Call_Channel__c` as call_channel,
  `Call_Type_vod__c` as call_type,
  cast(null as string) as detail_group,
  cast(null as string) as owner_role,
  cast(null as string) as owner_id,
  `Owner_Name` as owner_name,
  `Territory_vod__c` as territory,
  cast(null as string) as location,
  cast(null as string) as parent_call_id,
  cast(null as string) as is_parent_call,
  cast(null as string) as is_group_call,
  `Duration_vod__c` as duration_min,
  cast(null as string) as has_signature,
  cast(null as string) as signature_datetime,
  cast(null as string) as currency_code,
  cast(null as string) as mobile_id,
  cast(null as string) as created_date,
  cast(null as string) as last_modified_date,
  cast(null as string) as call_year,
  cast(null as string) as call_quarter,
  cast(null as string) as call_dow,
  'N' as dq_account_missing,
  '{file_name}' as _source_file,
  '{batch_id}' as _batch_id,
  cast(current_timestamp() as string) as _load_ts,
  cast(current_timestamp() as string) as dwh_silver_ts,
  '{batch_id}' as dwh_batch_id,
  '{batch_id}' as batch_id,
  cast({file_id} as string) as pt_file_id
from {raw_filename}$qq$, 'commercial', 'crm', '*.xlsx', 'raw_to_curated', 'raw_call', 'call', '1');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  call_id,
  call_number,
  cast(null as string) as date_key,
  cast(null as string) as account_sk,
  cast(null as string) as owner_sk,
  cast(null as string) as territory_sk,
  call_date,
  call_quarter,
  call_year,
  call_dow,
  status,
  is_completed,
  call_channel,
  call_type,
  detail_group,
  owner_role,
  is_parent_call,
  is_group_call,
  duration_min,
  has_signature,
  currency_code,
  cast(null as string) as detail_count,
  cast(null as string) as discussion_count,
  cast(null as string) as negative_reaction_count,
  cast(null as string) as expense_total,
  cast(null as string) as expense_count,
  cast(null as string) as followup_count,
  dq_account_missing,
  'call' as data_src_nm
from {curated_db}.{curated_tbl_name}
where batch_id = '{batch_id}'$qq$, 'commercial', 'crm', '*.xlsx', 'curated_to_publish', 'call', 'fact_call', '1');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  cast(null as string) as line_id,
  cast(null as string) as line_number,
  `Call2_vod__c` as call_id,
  `Product_vod__c` as product_id,
  `Product_Name_vod__c` as product_name,
  cast(null as string) as detail_group,
  `Detail_Priority_vod__c` as detail_priority,
  cast(null as string) as detail_order,
  '{file_name}' as _source_file,
  '{batch_id}' as _batch_id,
  cast(current_timestamp() as string) as _load_ts,
  'N' as dq_call_missing,
  cast(current_timestamp() as string) as dwh_silver_ts,
  '{batch_id}' as dwh_batch_id,
  '{batch_id}' as batch_id,
  cast({file_id} as string) as pt_file_id
from {raw_filename}$qq$, 'commercial', 'crm', '*.xlsx', 'raw_to_curated', 'raw_call_detail', 'call_detail', '1');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  line_id,
  call_id,
  cast(null as string) as date_key,
  cast(null as string) as product_sk,
  product_id,
  product_name,
  detail_group,
  detail_priority,
  detail_order,
  dq_call_missing,
  'call_detail' as data_src_nm
from {curated_db}.{curated_tbl_name}
where batch_id = '{batch_id}'$qq$, 'commercial', 'crm', '*.xlsx', 'curated_to_publish', 'call_detail', 'fact_call_detail', '1');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  cast(null as string) as line_id,
  cast(null as string) as line_number,
  `Call2_vod__c` as call_id,
  `Product_vod__c` as product_id,
  `Product_vod__c` as product_name,
  `Topic_vod__c` as topic,
  `Reaction_vod__c` as reaction,
  '{file_name}' as _source_file,
  '{batch_id}' as _batch_id,
  cast(current_timestamp() as string) as _load_ts,
  cast(null as string) as is_negative_reaction,
  cast(null as string) as is_info_request,
  'N' as dq_call_missing,
  cast(current_timestamp() as string) as dwh_silver_ts,
  '{batch_id}' as dwh_batch_id,
  '{batch_id}' as batch_id,
  cast({file_id} as string) as pt_file_id
from {raw_filename}$qq$, 'commercial', 'crm', '*.xlsx', 'raw_to_curated', 'raw_call_discussion', 'call_discussion', '1');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  line_id,
  call_id,
  cast(null as string) as date_key,
  cast(null as string) as product_sk,
  product_id,
  product_name,
  topic,
  reaction,
  is_negative_reaction,
  is_info_request,
  dq_call_missing,
  'call_discussion' as data_src_nm
from {curated_db}.{curated_tbl_name}
where batch_id = '{batch_id}'$qq$, 'commercial', 'crm', '*.xlsx', 'curated_to_publish', 'call_discussion', 'fact_call_discussion', '1');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  cast(null as string) as line_id,
  cast(null as string) as line_number,
  `Call2_vod__c` as call_id,
  `Expense_Type_vod__c` as expense_type,
  `Amount_vod__c` as amount,
  cast(null as string) as attendee_account_id,
  cast(null as string) as currency_code,
  `Expense_Date_vod__c` as expense_date,
  '{file_name}' as _source_file,
  '{batch_id}' as _batch_id,
  cast(current_timestamp() as string) as _load_ts,
  'N' as dq_call_missing,
  cast(current_timestamp() as string) as dwh_silver_ts,
  '{batch_id}' as dwh_batch_id,
  '{batch_id}' as batch_id,
  cast({file_id} as string) as pt_file_id
from {raw_filename}$qq$, 'commercial', 'crm', '*.xlsx', 'raw_to_curated', 'raw_call_expense', 'call_expense', '1');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  line_id,
  call_id,
  cast(null as string) as date_key,
  cast(null as string) as expense_date_key,
  cast(null as string) as owner_sk,
  cast(null as string) as territory_sk,
  cast(null as string) as attendee_sk,
  expense_type,
  amount,
  currency_code,
  expense_date,
  dq_call_missing,
  'call_expense' as data_src_nm
from {curated_db}.{curated_tbl_name}
where batch_id = '{batch_id}'$qq$, 'commercial', 'crm', '*.xlsx', 'curated_to_publish', 'call_expense', 'fact_call_expense', '1');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  cast(null as string) as line_id,
  cast(null as string) as line_number,
  `Call2_vod__c` as call_id,
  `Activity_Type_vod__c` as activity_type,
  `Due_date_vod__c` as due_date,
  `Product_vod__c` as product_id,
  cast(null as string) as description,
  '{file_name}' as _source_file,
  '{batch_id}' as _batch_id,
  cast(current_timestamp() as string) as _load_ts,
  cast(null as string) as is_overdue,
  'N' as dq_call_missing,
  cast(current_timestamp() as string) as dwh_silver_ts,
  '{batch_id}' as dwh_batch_id,
  '{batch_id}' as batch_id,
  cast({file_id} as string) as pt_file_id
from {raw_filename}$qq$, 'commercial', 'crm', '*.xlsx', 'raw_to_curated', 'raw_call_followup', 'call_followup', '1');
INSERT INTO query_configuration (source_system, sql_query, domain, sub_domain, file_name, interface, source_tablename, target_tablename, priority_column) VALUES ('veeva_crm', $qq$select
  line_id,
  call_id,
  cast(null as string) as date_key,
  cast(null as string) as due_date_key,
  cast(null as string) as product_sk,
  activity_type,
  due_date,
  is_overdue,
  description,
  dq_call_missing,
  'call_followup' as data_src_nm
from {curated_db}.{curated_tbl_name}
where batch_id = '{batch_id}'$qq$, 'commercial', 'crm', '*.xlsx', 'curated_to_publish', 'call_followup', 'fact_call_followup', '1');

-- 3. stitching_configuration — 'full' overwrite per table
DELETE FROM stitching_configuration WHERE dl_source='veeva_crm';
INSERT INTO stitching_configuration (dl_source, pt_pattern_name, pattern_name, source_database_name, source_table_name, target_database_name, target_table_name, stitching_type, primary_keys, order_key, record_load_key, active_flag) VALUES ('veeva_crm', 'account_#.xlsx', 'account', 'medaffairs_silver', 'account', 'medaffairs_gold', 'dim_account', 'full', '', '', '', 'A');
INSERT INTO stitching_configuration (dl_source, pt_pattern_name, pattern_name, source_database_name, source_table_name, target_database_name, target_table_name, stitching_type, primary_keys, order_key, record_load_key, active_flag) VALUES ('veeva_crm', 'call_#.xlsx', 'call', 'medaffairs_silver', 'call', 'medaffairs_gold', 'fact_call', 'full', '', '', '', 'A');
INSERT INTO stitching_configuration (dl_source, pt_pattern_name, pattern_name, source_database_name, source_table_name, target_database_name, target_table_name, stitching_type, primary_keys, order_key, record_load_key, active_flag) VALUES ('veeva_crm', 'call_detail_#.xlsx', 'call_detail', 'medaffairs_silver', 'call_detail', 'medaffairs_gold', 'fact_call_detail', 'full', '', '', '', 'A');
INSERT INTO stitching_configuration (dl_source, pt_pattern_name, pattern_name, source_database_name, source_table_name, target_database_name, target_table_name, stitching_type, primary_keys, order_key, record_load_key, active_flag) VALUES ('veeva_crm', 'call_discussion_#.xlsx', 'call_discussion', 'medaffairs_silver', 'call_discussion', 'medaffairs_gold', 'fact_call_discussion', 'full', '', '', '', 'A');
INSERT INTO stitching_configuration (dl_source, pt_pattern_name, pattern_name, source_database_name, source_table_name, target_database_name, target_table_name, stitching_type, primary_keys, order_key, record_load_key, active_flag) VALUES ('veeva_crm', 'call_expense_#.xlsx', 'call_expense', 'medaffairs_silver', 'call_expense', 'medaffairs_gold', 'fact_call_expense', 'full', '', '', '', 'A');
INSERT INTO stitching_configuration (dl_source, pt_pattern_name, pattern_name, source_database_name, source_table_name, target_database_name, target_table_name, stitching_type, primary_keys, order_key, record_load_key, active_flag) VALUES ('veeva_crm', 'call_followup_#.xlsx', 'call_followup', 'medaffairs_silver', 'call_followup', 'medaffairs_gold', 'fact_call_followup', 'full', '', '', '', 'A');

-- 4. clean ledger so the next run processes from scratch
DELETE FROM dl_ingestion_log;
DELETE FROM file_process_log;
DELETE FROM parent_batch_process WHERE source_system='veeva_crm';
COMMIT;
